In [1]:
pip install pandas numpy sentence-transformers scikit-learn flask

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 5.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 114.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 87.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 58.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 1.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 5.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 12.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 7.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 6.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 100.7 MB/s eta 0:00:00
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitl

In [2]:
pip install YOLO

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.2/56.2 kB 3.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 122.5/122.5 kB 9.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.4/13.4 MB 115.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.6/4.6 MB 109.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.6/139.6 kB 15.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 117.7/117.7 kB 12.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 548.2/548.2 kB 37.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 739.1/739.1 kB 53.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.4/84.4 kB 8.6 MB/s eta 0:00:00
  Attempting uninstall: keyring
    Found existing installation: keyring 23.5.0
    Uninstalling keyring-23.5.0:
      Successfully uninstalled keyring-23.5.0
  Attempting uninstall: rsa
    Found existing installation: rsa 4.9
    Uninstalling rsa-4.9:
      Successfully uninstall

In [3]:
!pip install ultralytics

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 949.2/949.2 kB 14.1 MB/s eta 0:00:00


import statements

In [40]:
import pandas as pd
import numpy as np
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
from ultralytics import YOLO
import cv2
from sklearn.cluster import KMeans
from collections import Counter
import os
from google.colab import drive

In [5]:
data = pd.read_csv("/content/merged_fashion.csv", on_bad_lines="skip")
data.head()

id gender masterCategory subCategory  articleType baseColour  season  \
0  15970    Men        Apparel     Topwear       Shirts  Navy Blue    Fall   
1  39386    Men        Apparel  Bottomwear        Jeans       Blue  Summer   
2  59263  Women    Accessories     Watches      Watches     Silver  Winter   
3  21379    Men        Apparel  Bottomwear  Track Pants      Black    Fall   
4  53759    Men        Apparel     Topwear      Tshirts       Grey  Summer   

     year   usage                             productDisplayName  \
0  2011.0  Casual               Turtle Check Men Navy Blue Shirt   
1  2012.0  Casual             Peter England Men Party Blue Jeans   
2  2016.0  Casual                       Titan Women Silver Watch   
3  2011.0  Casual  Manchester United Men Solid Black Track Pants   
4  2012.0  Casual                          Puma Men Grey T-shirt   

                                           json_data  filename  link  
0  {'notification': {}, 'meta': {'code': 200, 're...       NaN   NaN  
1  {'notification': {}, 'meta': {'code': 200, 're...       NaN   NaN  
2  {'notification': {}, 'meta': {'code': 200, 're...       NaN   NaN  
3  {'notification': {}, 'meta': {'code': 200, 're...       NaN   NaN  
4  {'notification': {}, 'meta': {'code': 200, 're...       NaN   NaN

In [6]:
if data[['filename', 'link']].isna().all().all():
    data.drop(columns=['filename', 'link'], inplace=True)

In [7]:
data.head()

id gender masterCategory subCategory  articleType baseColour  season  \
0  15970    Men        Apparel     Topwear       Shirts  Navy Blue    Fall   
1  39386    Men        Apparel  Bottomwear        Jeans       Blue  Summer   
2  59263  Women    Accessories     Watches      Watches     Silver  Winter   
3  21379    Men        Apparel  Bottomwear  Track Pants      Black    Fall   
4  53759    Men        Apparel     Topwear      Tshirts       Grey  Summer   

     year   usage                             productDisplayName  \
0  2011.0  Casual               Turtle Check Men Navy Blue Shirt   
1  2012.0  Casual             Peter England Men Party Blue Jeans   
2  2016.0  Casual                       Titan Women Silver Watch   
3  2011.0  Casual  Manchester United Men Solid Black Track Pants   
4  2012.0  Casual                          Puma Men Grey T-shirt   

                                           json_data  
0  {'notification': {}, 'meta': {'code': 200, 're...  
1  {'notification': {}, 'meta': {'code': 200, 're...  
2  {'notification': {}, 'meta': {'code': 200, 're...  
3  {'notification': {}, 'meta': {'code': 200, 're...  
4  {'notification': {}, 'meta': {'code': 200, 're...

PHASE 1 : Model that recommends outfits based on occasion

In [8]:
# Initialize Sentence-BERT model
model = SentenceTransformer("all-MiniLM-L6-v2")

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [9]:
# Encode product descriptions
data["text_data"] = data["productDisplayName"] + " " + data["json_data"]  # Merge relevant text
text_embeddings = model.encode(data["text_data"], show_progress_bar=True)

# Save embeddings for reuse
np.save("text_embeddings.npy", text_embeddings)
data.to_csv("fashion_data_with_embeddings.csv", index=False)

Batches:   0%|          | 0/1389 [00:00<?, ?it/s]

In [10]:
# Load precomputed embeddings
text_embeddings = np.load("text_embeddings.npy")

In [11]:
# Load image dataset
image_df = pd.read_csv("/content/images.csv")
image_df["filename"] = image_df["filename"].astype(str)

In [12]:
# Ensure both columns are strings
data["id"] = data["id"].astype(str)
image_df["filename"] = image_df["filename"].astype(str).str.replace(".jpg", "", regex=False)

# Merge datasets
df = data.merge(image_df, left_on="id", right_on="filename", how="left")

# Drop redundant filename column
df.drop(columns=["filename"], inplace=True)

# Print first 5 rows to check
print(df.head())

      id gender masterCategory subCategory  articleType baseColour  season  \
0  15970    Men        Apparel     Topwear       Shirts  Navy Blue    Fall   
1  39386    Men        Apparel  Bottomwear        Jeans       Blue  Summer   
2  59263  Women    Accessories     Watches      Watches     Silver  Winter   
3  21379    Men        Apparel  Bottomwear  Track Pants      Black    Fall   
4  53759    Men        Apparel     Topwear      Tshirts       Grey  Summer   

     year   usage                             productDisplayName  \
0  2011.0  Casual               Turtle Check Men Navy Blue Shirt   
1  2012.0  Casual             Peter England Men Party Blue Jeans   
2  2016.0  Casual                       Titan Women Silver Watch   
3  2011.0  Casual  Manchester United Men Solid Black Track Pants   
4  2012.0  Casual                          Puma Men Grey T-shirt   

                                           json_data  \
0  {'notification': {}, 'meta': {'code': 200, 're...   
1  {'notif

In [13]:
def recommend_outfits(user_input, top_n=5, min_similarity=0.6, season=None, base_color=None, gender=None, master_category=None, sub_category=None):
    """Finds top fashion items matching user input with optional filtering, ensuring results are always returned."""
    user_embedding = model.encode([user_input])  # Encode user query
    similarities = cosine_similarity(user_embedding, text_embeddings)[0]  # Compute similarity

    # Get top matches sorted by similarity
    top_indices = np.argsort(similarities)[::-1][:top_n]

    # Get recommended items
    recommendations = data.iloc[top_indices][["productDisplayName", "gender", "masterCategory",
                                              "subCategory", "articleType", "baseColour", "season"]].copy()

    # Apply optional filters
    if season:
        recommendations = recommendations[recommendations["season"].str.lower() == season.lower()]
    if base_color:
        recommendations = recommendations[recommendations["baseColour"].str.lower() == base_color.lower()]
    if gender:
        recommendations = recommendations[recommendations["gender"].str.lower() == gender.lower()]
    if master_category:
        recommendations = recommendations[recommendations["masterCategory"].str.lower() == master_category.lower()]
    if sub_category:
        recommendations = recommendations[recommendations["subCategory"].str.lower() == sub_category.lower()]

    # ✅ If all filters remove results, return top closest matches without filtering
    if recommendations.empty:
        return data.iloc[top_indices][["productDisplayName", "gender", "masterCategory",
                                       "subCategory", "articleType", "baseColour", "season"]]

    return recommendations

In [14]:
print(recommend_outfits("Casual winter dinner outfit", season="Winter"))

                                      productDisplayName gender  \
2065                  FNF Multi Colour Evening Wear Sari  Women   
16194  U.S. Polo Assn. Men Cream-Coloured Tailored Fi...    Men   
17503                FNF Multicoloured Evening Wear Sari  Women   
42901  Satya Paul Women Multi Coloured Georgette Prin...  Women   
26606  109F Women Black & Cream-Coloured Colourblocke...  Women   

      masterCategory subCategory articleType baseColour  season  
2065         Apparel       Saree      Sarees      Multi    Fall  
16194        Apparel     Topwear      Shirts      Cream  Summer  
17503        Apparel       Saree      Sarees      Multi    Fall  
42901        Apparel     Topwear      Tunics      Multi    Fall  
26606        Apparel     Topwear      Tunics      Black  Summer  


PHASE 2:Model that recommends pieces to complete the existing outfit

In [19]:
# Load a general YOLOv8 model
model = YOLO("yolov8m.pt")

100%|██████████| 49.7M/49.7M [00:00<00:00, 264MB/s]


In [20]:
image_paths = ["/content/outfit1.jpg", "/content/outfit2.jpg"]

In [21]:
# Run detection on both images
results = [model(cv2.imread(img)) for img in image_paths]


0: 640x384 1 bottle, 104.7ms
Speed: 14.6ms preprocess, 104.7ms inference, 227.3ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 1 person, 2 handbags, 1 chair, 1 potted plant, 1 cell phone, 1 vase, 25.3ms
Speed: 3.1ms preprocess, 25.3ms inference, 1.5ms postprocess per image at shape (1, 3, 640, 384)


In [25]:
def get_dominant_colors(image, k=3):
    """Extracts the top k dominant colors from the image."""
    image = cv2.resize(image, (100, 100))  # Resize for faster processing
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)  # Convert to RGB
    pixels = image.reshape(-1, 3)  # Reshape to 1D array

    kmeans = KMeans(n_clusters=k)
    kmeans.fit(pixels)

    colors = kmeans.cluster_centers_.astype(int)  # Get dominant colors
    return colors

In [26]:
def analyze_outfit(image_path):
    """Runs YOLO detection, and if no reliable results, extracts colors & patterns."""
    image = cv2.imread(image_path)
    results = model(image)  # Run YOLO detection

    detected_items = []
    for box in results[0].boxes:
        confidence = box.conf[0].item()
        if confidence >= 0.5:
            class_id = int(box.cls[0])
            detected_items.append(model.names[class_id])

    if detected_items:
        print(f"\n🔹 **Detected Clothing Items:** {detected_items}")
    else:
        print("\n⚠️ No reliable detections found! Extracting colors & patterns instead...")

        # Extract dominant colors
        colors = get_dominant_colors(image)
        print(f"🎨 **Dominant Colors:** {colors}")

        # Detect edges to check for patterns
        gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
        edges = cv2.Canny(gray, 100, 200)  # Edge detection
        pattern_intensity = np.sum(edges) / edges.size  # Measure edge density

        pattern_type = "Solid" if pattern_intensity < 50 else "Patterned"
        print(f"🖼️ **Pattern Type:** {pattern_type}")


In [27]:
# Test with images
image_paths = ["outfit1.jpg", "outfit2.jpg"]
for img_path in image_paths:
    analyze_outfit(img_path)


0: 640x384 1 bottle, 25.8ms
Speed: 3.1ms preprocess, 25.8ms inference, 1.5ms postprocess per image at shape (1, 3, 640, 384)

⚠️ No reliable detections found! Extracting colors & patterns instead...
🎨 **Dominant Colors:** [[253 253 252]
 [ 63  54  66]
 [175 182 183]]
🖼️ **Pattern Type:** Solid

0: 640x384 1 person, 2 handbags, 1 chair, 1 potted plant, 1 cell phone, 1 vase, 25.3ms
Speed: 3.2ms preprocess, 25.3ms inference, 1.8ms postprocess per image at shape (1, 3, 640, 384)

🔹 **Detected Clothing Items:** ['person', 'handbag']


In [34]:
def suggest_outfit_completions(detected_items, colors, pattern_type, occasion="Casual"):
    """Suggests missing outfit pieces based on detected clothing items."""

    detected_categories = set(data[data['articleType'].isin(detected_items)]['subCategory'])
    essential_categories = {"Topwear", "Bottomwear", "Footwear", "Accessories"}
    missing_categories = essential_categories - detected_categories

    suggestions = []
    for category in missing_categories:
        filtered_data = data[data['subCategory'] == category].copy()  # Copy to avoid SettingWithCopyWarning

        # Filter by occasion (if available)
        if "occasion" in data.columns:
            filtered_data = filtered_data[filtered_data["occasion"].str.contains(occasion, na=False, case=False)]

        # Sort by best color/pattern match
        if "baseColour" in data.columns:
            filtered_data.loc[:, "color_match"] = filtered_data["baseColour"].apply(
                lambda x: any(str(c) in str(x).lower() for c in colors)
            )
            filtered_data = filtered_data.sort_values(by="color_match", ascending=False)

        # Select top suggestion
        if not filtered_data.empty:
            suggestions.append(filtered_data.iloc[0]["productDisplayName"])

    return suggestions

In [35]:
def analyze_outfit_and_suggest(image_path, occasion="Casual"):
    """Runs outfit analysis and suggests missing pieces."""
    image = cv2.imread(image_path)
    results = model(image)  # Run YOLO detection

    detected_items = []
    for box in results[0].boxes:
        confidence = box.conf[0].item()
        if confidence >= 0.5:
            class_id = int(box.cls[0])
            detected_items.append(model.names[class_id])

    if detected_items:
        print(f"\n🔹 **Detected Clothing Items:** {detected_items}")
    else:
        print("\n⚠️ No reliable detections found! Extracting colors & patterns instead...")
        detected_items = []

    # Extract dominant colors
    colors = get_dominant_colors(image)
    print(f"🎨 **Dominant Colors:** {colors}")

    # Detect patterns
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    edges = cv2.Canny(gray, 100, 200)
    pattern_intensity = np.sum(edges) / edges.size
    pattern_type = "Solid" if pattern_intensity < 50 else "Patterned"
    print(f"🖼️ **Pattern Type:** {pattern_type}")

    # Suggest outfit completions
    suggestions = suggest_outfit_completions(detected_items, colors, pattern_type, occasion)
    print(f"\n✨ **Suggested Missing Pieces for {occasion}:** {suggestions}")

In [36]:
# Test
analyze_outfit_and_suggest("outfit1.jpg", "Winter Party")
analyze_outfit_and_suggest("outfit2.jpg", "Casual Summer")


0: 640x384 1 bottle, 25.5ms
Speed: 3.9ms preprocess, 25.5ms inference, 1.5ms postprocess per image at shape (1, 3, 640, 384)

⚠️ No reliable detections found! Extracting colors & patterns instead...
🎨 **Dominant Colors:** [[253 253 252]
 [ 63  54  66]
 [175 181 183]]
🖼️ **Pattern Type:** Solid

✨ **Suggested Missing Pieces for Winter Party:** ['Peter England Men Party Blue Jeans', 'Turtle Check Men Navy Blue Shirt', 'Wildcraft Unisex Rust Orange Travel Pouch']

0: 640x384 1 person, 2 handbags, 1 chair, 1 potted plant, 1 cell phone, 1 vase, 25.4ms
Speed: 2.5ms preprocess, 25.4ms inference, 1.7ms postprocess per image at shape (1, 3, 640, 384)

🔹 **Detected Clothing Items:** ['person', 'handbag']
🎨 **Dominant Colors:** [[ 85  56  46]
 [226 212 205]
 [184 146 133]]
🖼️ **Pattern Type:** Solid

✨ **Suggested Missing Pieces for Casual Summer:** ['Peter England Men Party Blue Jeans', 'Turtle Check Men Navy Blue Shirt', 'Wildcraft Unisex Rust Orange Travel Pouch']


In [37]:
TEXT_EMBEDDINGS_PATH = "/content/text_embeddings.npy"
YOLO_CLOTHES_MODEL = "/content/yolov8m-clothes.pt"
YOLO_GENERAL_MODEL = "/content/yolov8m.pt"

In [39]:
for file in ["text_embeddings.npy", "yolov8m-clothes.pt", "yolov8m.pt"]:
    print(f"{file} exists: {os.path.exists(file)}")

text_embeddings.npy exists: True
yolov8m-clothes.pt exists: True
yolov8m.pt exists: True


In [41]:
drive.mount('/content/drive')

Mounted at /content/drive


In [43]:
# Define the project folder in Google Drive
project_folder = "/content/drive/MyDrive/your_project"

# Create the directory if it does not exist
os.makedirs(project_folder, exist_ok=True)

# Move the files
!mv yolov8m.pt "$project_folder/"
!mv yolov8m-clothes.pt "$project_folder/"
!mv text_embeddings.npy "$project_folder/"

print("Files moved successfully!")

Files moved successfully!
